In [1]:
print("Hello World")

Hello World


In [2]:

print(2 + 2)
print(4 - 7)
print(7 * 32.46)
print(3 / 2.2)
print(3 ** 2)

4
-3
227.22
1.3636363636363635
9


In [3]:
print(my_favorite_variable)

NameError: name 'my_favorite_variable' is not defined

In [4]:
print = 43

In [5]:
print(print)

TypeError: 'int' object is not callable

In [3]:
P = 1000
r = 0.07
n = 12
t = 5

In [6]:
A = P * (1 + r/n)**(n * t)
print(A-P)

417.62525961399024


In [10]:
truth = True
falsehood = False

print(truth)
print(falsehood)

print(truth + falsehood)
print(truth - falsehood)
print(truth * falsehood)
print(truth ** falsehood)
print(truth / falsehood)

True
False
1
1
0
1


ZeroDivisionError: division by zero

In [11]:
errorful_string = "This is a bad string'

SyntaxError: EOL while scanning string literal (<ipython-input-11-63e6e29c6503>, line 1)

In [13]:
my_name = "eric johnson"
my_name.capitalize()
my_name.title()


'Eric johnson'

'Eric Johnson'

In [15]:
number_str = "1234"
print(f"'number_str' = {number_str} is type {type(number_str)}")
floated_number_str = float(number_str)
print(f"'floated_number_str' = {floated_number_str} is type {type(floated_number_str)}")


'number_str' = 1234 is type <class 'str'>
'floated_number_str' = 1234.0 is type <class 'float'>


In [16]:
pos1 = 2.1
pos2 = 1.9

neg1 = -2.1
neg2 = -1.9

int_pos1 = int(pos1)
int_pos2 = int(pos2)

int_neg1 = int(neg1)
int_neg2 = int(neg2)

## Comment this out AFTER you have made your predictions.
print(f"int('pos1' = {pos1}) is {int_pos1}")
print(f"int('pos2' = {pos2}) is {int_pos2}")
print()
print(f"int('neg1' = {neg1}) is {int_neg1}")
print(f"int('neg2' = {neg2}) is {int_neg2}")

int('pos1' = 2.1) is 2
int('pos2' = 1.9) is 1

int('neg1' = -2.1) is -2
int('neg2' = -1.9) is -1


In [20]:

pos_int = 4
neg_int = -3
zero_int = 0

pos_float = 7.13
small_pos_float = 0.0003
neg_float = -4.67
zero_float = 0.0

number_str = "3.12"
zero_number_str = "0"
letter_str = "abcdef"
empty_str = "" ## What is this??? Check the type!

print(f"Converting {pos_int} to boolean gives {bool(pos_int)}")
print(f"Converting {neg_int} to boolean gives {bool(neg_int)}")
print(f"Converting {zero_int} to boolean gives {bool(zero_int)}")

print(f"\nConverting {pos_float} to boolean gives {bool(pos_float)}")
print(f"Converting {small_pos_float} to boolean gives {bool(small_pos_float)}")
print(f"Converting {neg_float} to boolean gives {bool(neg_float)}")
print(f"Converting {zero_float} to boolean gives {bool(zero_float)}")

print(f"\nConverting {number_str} to boolean gives {bool(number_str)}")
print(f"Converting {zero_number_str} to boolean gives {bool(zero_number_str)}")
print(f"Converting {letter_str} to boolean gives {bool(letter_str)}")
print(f"Converting {empty_str} to boolean gives {bool(empty_str)}")

Converting 4 to boolean gives True
Converting -3 to boolean gives True
Converting 0 to boolean gives False

Converting 7.13 to boolean gives True
Converting 0.0003 to boolean gives True
Converting -4.67 to boolean gives True
Converting 0.0 to boolean gives False

Converting 3.12 to boolean gives True
Converting 0 to boolean gives True
Converting abcdef to boolean gives True
Converting  to boolean gives False


In [21]:
a, b = "e", "j"
output = (a = b)

SyntaxError: invalid syntax (<ipython-input-21-bba329a5f0ed>, line 2)

In [22]:

crazy_list = ['abcd', [12, 4, 'no'], ['yes', [True, 'unique element']], 'False', False]
print(crazy_list)

third_crazy_element = crazy_list[2]
print(third_crazy_element)

second_third_crazy_element = third_crazy_element[1]
print(second_third_crazy_element)

second_second_third_crazy_element = second_third_crazy_element[1]
print(second_second_third_crazy_element)

other_element = crazy_list[2][1][1]  ## What's happening here!?
print(other_element)

['abcd', [12, 4, 'no'], ['yes', [True, 'unique element']], 'False', False]
['yes', [True, 'unique element']]
[True, 'unique element']
unique element
unique element


In [24]:

third_crazy_element = crazy_list[2]
print(f"The length of the third element is {len(third_crazy_element)}")

second_third_crazy_element = third_crazy_element[1]
print(f"The length of the second-third element is {len(second_third_crazy_element)}")

# Uncomment and read the error message!
second_second_third_crazy_element = second_third_crazy_element[1]
print(f"The length of the second-second-third element is {len(second_second_third_crazy_element)}")

The length of the third element is 2
The length of the second-third element is 2
The length of the second-second-third element is 14


In [27]:
bool(['True'])
bool([])
bool([True])

True

False

True

In [28]:
second_second_third_crazy_element = 10
print(crazy_list)

['abcd', [12, 4, 'no'], ['yes', [True, 'unique element']], 'False', False]


In [29]:
new_list = crazy_list
new_list[2][1][1] = 10
print(crazy_list)

['abcd', [12, 4, 'no'], ['yes', [True, 10]], 'False', False]


In [35]:
new_list.insert(2, 'turtle')

In [36]:
new_list

['abcd',
 [12, 4, 'no'],
 'turtle',
 'gecko',
 'gecko',
 ['yes', [True, 10]],
 'False',
 False]

In [4]:

my_str = "the quick brown fox"
my_int = 6543
my_float = 65.43
my_bool = True or False

print(list(my_str))  ## What happened here!?
# print(list(my_int))
# print(list(my_float))
# print(list(my_bool))

['t', 'h', 'e', ' ', 'q', 'u', 'i', 'c', 'k', ' ', 'b', 'r', 'o', 'w', 'n', ' ', 'f', 'o', 'x']


In [9]:

start, stop, step = 0, 10, 2
my_range1 = range(start, stop, step)
print(my_range1)
print(type(my_range1))  ## What type does 'my_range1' appear to be?

## Apply the list() function:
my_range1 = list(my_range1)  
print(my_range1)
print(type(my_range1))

## If we don't supply a step size, it increments by 1
print(list(range(start, stop)))

## If we don't supply a starting point, it assumes 0
print(list(range(stop)))

## We can use negative step sizes
print(list(range(stop, start, -step)))

## Is 'stop'=10 in this list?
print(list(range(10)))

## What happens if we try to use a float?
# print(list(range(10.1)))

range(0, 10, 2)
<class 'range'>
[0, 2, 4, 6, 8]
<class 'list'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 8, 6, 4, 2]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


TypeError: 'float' object cannot be interpreted as an integer

In [12]:

num_list = list([3, 6.3, 8, 12.52, 4, 4, 3, True])
avg_of_list = sum(num_list) / len(num_list)
print(f"The average value of 'num_list' is {avg_of_list}")

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [13]:
names_colors = [['Eric', 'purple'], ['Anya', 'green'], ['Juan', 'blue'], ['Zach', 'blue'], ['Florencia', 'red']]
sorted(names_colors)

[['Anya', 'green'],
 ['Eric', 'purple'],
 ['Florencia', 'red'],
 ['Juan', 'blue'],
 ['Zach', 'blue']]

In [15]:
sorted(names_colors, key = lambda x: x[1])

[['Juan', 'blue'],
 ['Zach', 'blue'],
 ['Anya', 'green'],
 ['Eric', 'purple'],
 ['Florencia', 'red']]

In [17]:
names_colors[0].count('Eric')

1

In [18]:

num_list = list([3, 6.3, 8, 12.52, 4, 4, 3, True, 3])
avg_of_list = sum(num_list) / len(num_list)
print(f"The average value of 'num_list' is {avg_of_list}")

num_3 = num_list.count(3)
num_4 = num_list.count(4)
num_8 = num_list.count(8)
print(f"There are {num_3} 3s in 'num_list'")
print(f"There are {num_4} 4s in 'num_list'")
print(f"There are {num_8} 8s in 'num_list'")

The average value of 'num_list' is 4.98
There are 3 3s in 'num_list'
There are 2 4s in 'num_list'
There are 1 8s in 'num_list'


In [20]:
num_list.index(4)

4

In [22]:

num_list = list([3, 6.3, 8, 12.52, 4, 4, 3, True, 3, 0.1])
list_max = max(num_list)
list_min = min(num_list)
list_sum = sum(num_list)

print(f"The max of 'num_list' is {list_max}")
print(f"The min of 'num_list' is {list_min}")
print(f"The sum of 'num_list' is {list_sum}")

The max of 'num_list' is 12.52
The min of 'num_list' is 0.1
The sum of 'num_list' is 44.92


In [23]:
num_list.reverse()
print(num_list)

[0.1, 3, True, 3, 4, 4, 12.52, 8, 6.3, 3]


In [24]:

num_list = list([3, 6.3, 8, 12.52, 4, 4, 3, True, 3, 0.1])
num_arr = np.array(num_list)
print(num_arr)
print(type(num_arr))

n_rows, n_cols = 5, 3
empty_arr = np.empty((n_rows, n_cols)) ## SYNTAX ALERT NOTE THE DOUBLE
									   ## PARENTHESES
zero_arr = np.zeros((n_rows, n_cols))
one_arr = np.ones((n_rows, n_cols))

print(f"\nArrays of size {n_rows} x {n_cols}")
print("\nAn empty array:")
print(empty_arr)
print("\nAn zero array:")
print(zero_arr)
print("\nAn one array:")
print(one_arr)

[ 3.    6.3   8.   12.52  4.    4.    3.    1.    3.    0.1 ]
<class 'numpy.ndarray'>

Arrays of size 5 x 3

An empty array:
[[0.         0.         0.4472136 ]
 [0.0531494  0.18257419 0.4472136 ]
 [0.2125976  0.36514837 0.4472136 ]
 [0.4783446  0.54772256 0.4472136 ]
 [0.85039041 0.73029674 0.4472136 ]]

An zero array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

An one array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
np.array(4)

array(4)

In [30]:
np.zeros(4, 1)

TypeError: Cannot interpret '1' as a data type

In [31]:

n_rows, n_cols = 5, 3
zero_arr = np.zeros((n_rows, n_cols))
arr_shape = zero_arr.shape
arr_ndim = zero_arr.ndim
arr_datatype = zero_arr.dtype

print(f"The shape of 'zero_arr' is {arr_shape}")
print(f"The number of dimensions of 'zero_arr' is {arr_ndim}")
print(f"The type of data in 'zero_arr' is {arr_datatype}")

The shape of 'zero_arr' is (5, 3)
The number of dimensions of 'zero_arr' is 2
The type of data in 'zero_arr' is float64


In [32]:

more_cols = np.zeros((arr_shape[0], 10))
print(more_cols)

fewer_rows = np.ones((2, arr_shape[1]))
print(fewer_rows)

same_but_ones = np.ones_like(zero_arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [50]:

	big_arr = np.array(2 * (list('abcdefghijklmnopqrstuvwxyz') + ['aa', 'bb'])).reshape(8, -1)

	print(big_arr)

	print(f"The shape of 'big_arr' is {big_arr.shape}")
	print(f"The number of dimensions of 'big_arr' is {big_arr.ndim}")
	print(f"The type of data in 'big_arr' is {big_arr.dtype}\n")

	first_row = big_arr[0]
	first_col = big_arr[:, 0]

	print("The first row is:", first_row)
	print("The first column is:", first_col)

	subset1 = big_arr[1:3, 2:6]
	subset2 = big_arr[-3:, :5]
	print("\n'subset1' is:")
	print(subset1)
	print(f"The shape of 'subset1' is {subset1.shape}")
	print("'subset2' is:")
	print(subset2)
	print(f"The shape of 'subset2' is {subset2.shape}")

[['a' 'b' 'c' 'd' 'e' 'f' 'g']
 ['h' 'i' 'j' 'k' 'l' 'm' 'n']
 ['o' 'p' 'q' 'r' 's' 't' 'u']
 ['v' 'w' 'x' 'y' 'z' 'aa' 'bb']
 ['a' 'b' 'c' 'd' 'e' 'f' 'g']
 ['h' 'i' 'j' 'k' 'l' 'm' 'n']
 ['o' 'p' 'q' 'r' 's' 't' 'u']
 ['v' 'w' 'x' 'y' 'z' 'aa' 'bb']]
The shape of 'big_arr' is (8, 7)
The number of dimensions of 'big_arr' is 2
The type of data in 'big_arr' is <U2

The first row is: ['a' 'b' 'c' 'd' 'e' 'f' 'g']
The first column is: ['a' 'h' 'o' 'v' 'a' 'h' 'o' 'v']

'subset1' is:
[['j' 'k' 'l' 'm']
 ['q' 'r' 's' 't']]
The shape of 'subset1' is (2, 4)
'subset2' is:
[['h' 'i' 'j' 'k' 'l']
 ['o' 'p' 'q' 'r' 's']
 ['v' 'w' 'x' 'y' 'z']]
The shape of 'subset2' is (3, 5)


In [39]:
big_arr.dtype

dtype('<U2')

In [41]:
big_arr.shape

(4, 2, 7)

In [52]:

	reshaped_arr = np.array(range(20)).reshape(4, 5)

In [54]:
reshaped_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:

added_arr = reshaped_arr + 3.4
minus_arr = added_arr - reshaped_arr
mult_arr = (4 * reshaped_arr / 5.345)**2.3

print(added_arr, "\n")
print(minus_arr, "\n")
print(mult_arr)

[[ 3.4  4.4  5.4  6.4  7.4]
 [ 8.4  9.4 10.4 11.4 12.4]
 [13.4 14.4 15.4 16.4 17.4]
 [18.4 19.4 20.4 21.4 22.4]] 

[[3.4 3.4 3.4 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]
 [3.4 3.4 3.4 3.4 3.4]] 

[[  0.           0.51340282   2.52829204   6.42446746  12.4507705 ]
 [ 20.80124159  31.6377889   45.10074752  61.31478619  80.39258987]
 [102.43732951 127.54440847 155.80274824 187.29576538 222.10213339]
 [260.29638936 301.9494259  347.12889615 395.89955158 448.32352704]]


In [65]:

	row_arr = np.arange(5)
	col_arr = np.arange(4).reshape(-1, 1)  ## WHAT DOES THE -1 DO HERE?
										   ## (check the shape!)
										   ## (try removing the reshape)
	print("\n'reshaped_array':")
	print(reshaped_arr)
	print("\n'row_arr':")
	print(row_arr)
	print("\n'col_arr':")
	print(col_arr)

	row_added = reshaped_arr + row_arr
	col_added = reshaped_arr + col_arr

	print("\nAdding a row array:")
	print(row_added)
	print("\nAdding a column array:")
	print(col_added)


'reshaped_array':
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

'row_arr':
[0 1 2 3 4]

'col_arr':
[[0]
 [1]
 [2]
 [3]]

Adding a row array:
[[ 0  2  4  6  8]
 [ 5  7  9 11 13]
 [10 12 14 16 18]
 [15 17 19 21 23]]

Adding a column array:
[[ 0  1  2  3  4]
 [ 6  7  8  9 10]
 [12 13 14 15 16]
 [18 19 20 21 22]]


In [63]:
np.hstack((reshaped_arr, reshaped_arr))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]])

In [70]:

	arr_mean = np.mean(reshaped_arr)
	row_mean = np.mean(reshaped_arr, axis=1)
	col_mean = np.mean(reshaped_arr, axis=0)
	print(f"The mean of 'reshaped_arr' is {arr_mean}")
	print(f"The row-wise mean of 'reshaped_arr' is {row_mean}")
	print(f"The column-wise mean of 'reshaped_arr' is {col_mean}")

The mean of 'reshaped_arr' is 9.5
The row-wise mean of 'reshaped_arr' is [ 2.  7. 12. 17.]
The column-wise mean of 'reshaped_arr' is [ 7.5  8.5  9.5 10.5 11.5]


In [67]:
row_mean

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [68]:
col_mean

array([ 2.,  7., 12., 17.])