In [1]:
import numpy as np ## It's good practice to put your imports right at the top!

# Loops

Now that we've learned about how data are stored in Python as different types that we can collect into [data structures](https://docs.python.org/3/tutorial/datastructures.html) like [lists](https://docs.python.org/3/c-api/list.html) or [numpy arrays](https://numpy.org/doc/stable/reference/generated/numpy.array.html), we should learn how to actually *do* things with our data! The next three sections on **loops**, [conditional statements](../05_ConditionalStatements/05_ConditionalStatements_Notebook), and [functions](../06_Functions/06_Functions_Notebook) will comprise the basics of everything you need to get yourself up and running with Python. This will also be your first introduction to Python's **syntax** (its "grammar" for how to structure code), beyond the simple syntax of variable assignment that we've seen thus far.

**Loops** are a natural place to start in the context of thinking about Python for data analysis because loops are a coding structure that tell computers how to execute a set of instructions repeatedly, and we often have lists or arrays of data that we want to iterate through ("loop over" in coding lingo) to perform calculations on each datum individually. That is, the term "loop" refers to the way that the computer *loops back* to do a set of tasks many times. This is one of the true superpowers of coding: computers have infinite patience and can do boring tasks repeatedly *ad nauseam*, so we can leverage this to make calculations or perform analyses that would be impossible to do by hand. We'll talk about this more when we learn about [random number generation](../10_RandomNumbers/10_RandomNumbers).

In Python there are three main types of loops: [`for`](https://docs.python.org/3/reference/compound_stmts.html#the-for-statement), [`while`](https://docs.python.org/3/reference/compound_stmts.html#while), and [**list comprehensions**](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions). `for` loops are probably the most common type and are the easiest to work with. `while` loops have a similar syntax to `for` loops, but are somewhat trickier and are a common source of bugs for novice coders. Finally, list comprehensions have a more complicated syntax, but are extremely "[Pythonic](https://www.computerhope.com/jargon/p/pythonic.htm)" and a nice way to compress loops that involve lists. In this tutorial, we'll mostly focus on `for` and `while` loops, but I'll introduce the list comprehension syntax so that you aren't stumped when you see it in the wild.  In this section, we'll learn about `for` loops, and we'll leave `while` loops for the next section, after we've introduced the notion of [conditional statements](../05_ConditionalStatements/05_ConditionalStatements_Notebook).

```{admonition} Big Idea
Loops are structure that tell the computer to *loop back and repeat* instructions several times.
```

## The `for` loop

At its most basic, a computer is a [bit](https://en.wikipedia.org/wiki/Bit)-moving and -storing machine; it can remember information and it can modify that information, but it at some level operates in a discrete, bit-by-bit manner. I say this because it can seem as though computers are doing many things simultaneously, but under the hood, operations like `sum([1, 12, 3, 6, 321])` are carried out by the computer as a set of *very fast*, simple, sequential steps:
- Set `tmp_sum = 0`
- `tmp_sum = tmp_sum + 1`
- `tmp_sum = tmp_sum + 12`
- `tmp_sum = tmp_sum + 3`
- `tmp_sum = tmp_sum + 6`
- `tmp_sum = tmp_sum + 321`
- return `tmp_sum` to the user.
The `for` loop is our structure to control this iterative process.

### What is a `for` loop?

The idea behind a `for` loop is that we are filling in the sentence "Do these steps *for* this many iterations." That is, we know how many times we want to do the operations, so the computer should do them for all the indicated repetitions. In Python, this is done by iterating over an **iterable** such as a list or array (tautologically, iterables are things that can be iterated over).

````{margin}
```{note}
Throughout this tutorial, I will highlight new terms and definitions, but the purpose for doing this is that you can use them as a reference to try and debug things later, not for you to try and memorize everything as you go.
```
````

As a simple example, consider the following:

In [2]:
for iteration in range(5):
    print("Doing some instructions!")

Doing some instructions!
Doing some instructions!
Doing some instructions!
Doing some instructions!
Doing some instructions!


Let's unpack this a bit.  The idea is that we can read this syntax as "for item in iterable: do stuff", where Python is going to do the **indented instructions** for each item in the list.  In this case, we're using the [`range`](https://docs.python.org/3/library/functions.html#func-range) function to create an iterable of length 5, and then Python is executing the indented instructions of `print("Doing some instructions!")` 5 times, once for each iteration in the iterable. We can do any normal Python commands in this indented area: variable assignment, calculations, even other loops as we'll see shortly!  For example:

In [3]:
n_iters = 4
for element in range(n_iters):
    print("\nThis is an iteration!")
    x = 3
    print("x has been assigned {}".format(x))



This is an iteration!
x has been assigned 3

This is an iteration!
x has been assigned 3

This is an iteration!
x has been assigned 3

This is an iteration!
x has been assigned 3


Where you can see that all of the indented instructions were executed `n_iters=4` times.

However, this is not all that lists can do. Earlier we suggested that we can iterate through lists and arrays, which would involve something *changing* about each iteration of the loop, and this is easy to do by taking advantage of the fact that Python loops automatically assign a value to the iterate variable specified in the `for` loop syntax. That is, in the previous examples, `iteration` and `element` were names given to a variable that actually stored a value based on the iterable provided.  We can see this in action below:

In [4]:
for iter_name in range(7):
    print(f"The value stored in 'iter_name' is {iter_name}")

The value stored in 'iter_name' is 0
The value stored in 'iter_name' is 1
The value stored in 'iter_name' is 2
The value stored in 'iter_name' is 3
The value stored in 'iter_name' is 4
The value stored in 'iter_name' is 5
The value stored in 'iter_name' is 6


Specifically, this iterator variable is being assigned the elements of the iterable (`range(7)` in the previous example) one at a time.  So in the case where we're using `range`, the variable `iter_name` recieves the elements of the iterable `range(7)` one at a time: first 0, then 1, then 2, and so on up to 6. You can check this by looking at the output of `print(list(range(7)))`.

````{margin}
```{admonition} Variable names
Remember, variables can have almost any name that you want, but it's good practice to make them informative. I've used `iteration`, `element`, and `iter_name` as examples.
```
````

We can do this with any iterable, not just the output of the `range` function, including lists.  For example:

In [5]:
list_of_pets = ['dogs', 'cats', 'iguanas', 'rabbits', 'birds']

for pet in list_of_pets:
    print(pet)

dogs
cats
iguanas
rabbits
birds


Here we can see that the iteration variable `pet` is being assigned each element of `list_of_pets` in turn.

It's important to note that this is a variable assignment that is happening at the `for` loop structure and not beforehand.  That is, we cannot access this `pet` variable until the loop has been run.

In [6]:
print(animal) ## This has not been assigned yet, so it will create a NameError!

for animal in pets:
    print(animal)

NameError: name 'animal' is not defined

Similarly, if `pet` was a variable we had created before the loop, it will be overwritten by the loop's assignment.

In [7]:
pet = "hamster"
print(pet)

for pet in list_of_pets:
    print("Pets are nice.")
    
print(pet)

hamster
Pets are nice.
Pets are nice.
Pets are nice.
Pets are nice.
Pets are nice.
birds


This means that we should make sure to use a distinct name for this iteration variable from previous variables. 

Also, you can note from the previous example that this variable persists after the loop and retains the value of the last assignment in the loop.  We'll see shortly that this is useful if you want to loop until a condition is met, after which you might want to keep the value of the iterator.  For example, if you want to know how many iterations it takes before some sort of calculation converges, you could use the value of the iteration variable.

#### Using a counter

It's worth noting that just because we have this iteration variable doesn't mean we have to use it.  It's relatively common to want to keep an external counter or incrementer to keep track of different things in the loop.  We can easily do this by initializing a variable before the loop and then incrementing (or decrementing) it in each loop iteration (or loop iterations that meet some criteria). As an example:

In [9]:
counter_var = 0 ## Initialize our counter at some value, here 0.

for itr in range(len(list_of_pets)):
    counter_var = counter_var + 1
    
print(f"The counter variable counted {counter_var} iterations!")

The counter variable counted 5 iterations!


#### Using the iterable in a loop

Another useful note is that we can still make use of the iterable variable inside the loop. We can even reassign its value, although this can have surprising results if you change the length of the iterable.

In [10]:
for pet in list_of_pets:
    print(list_of_pets)

['dogs', 'cats', 'iguanas', 'rabbits', 'birds']
['dogs', 'cats', 'iguanas', 'rabbits', 'birds']
['dogs', 'cats', 'iguanas', 'rabbits', 'birds']
['dogs', 'cats', 'iguanas', 'rabbits', 'birds']
['dogs', 'cats', 'iguanas', 'rabbits', 'birds']


In [14]:
list_of_pets = ['dogs', 'cats', 'iguanas', 'rabbits', 'birds']

for pet in list_of_pets:
    last_animal = list_of_pets.pop()
    
print(list_of_pets)

['dogs', 'cats']


### Exercise 4.1

1. Make a list of names, and use a loop to print out each name sequentially. Use some basic string formatting to make the output look nice.
2. Use a counter variable (or any other method) in the previous example to determine how many iterations the loop executed. Can you explain what happened to `list_of_pets` in this loop?

## Looping with indices

In the previous examples, we made use of the iteration variable in order to walk through the elements of a list (iterable), but the reason that the `range` function is so useful is because it provides a natural **index** with which we can access elements of a list or array via **slicing** as discussed in the [previous section](../03_Lists_Arrays/03_Lists_Arrays_Notebook).  As an example:

In [15]:
list_of_pets = ['dogs', 'cats', 'iguanas', 'rabbits', 'birds']

for index in range(len(list_of_pets)):
    element = list_of_pets[index]
    print(f"At index {index} the list contains {element}.")

At index 0 the list contains dogs.
At index 1 the list contains cats.
At index 2 the list contains iguanas.
At index 3 the list contains rabbits.
At index 4 the list contains birds.


We can also access elements of arrays by index:

In [16]:
myarray = np.arange(20)  ## What does this function do?
myarray = myarray.reshape(4, 5)
print(myarray)

for ii in range(4):
    print("This is row {}:".format(ii), myarray[ii])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
This is row 0: [0 1 2 3 4]
This is row 1: [5 6 7 8 9]
This is row 2: [10 11 12 13 14]
This is row 3: [15 16 17 18 19]
